server:
  port: 80
  
  
person:
    lastName: zhangsan
    age: 18
    boss: false
    birth: 2019/12/12
    map: {k1: v1,k2: 12}
    lists:
      - lisi
      - zhaoliu
    dog:
      name: 小狗
      age: 2
      